version: '3.3'
services:
  mongodb:
    image: mongo:4.4
    env_file:
      - ./mongo.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./init-mongodb.sh:/docker-entrypoint-initdb.d/init-mongodb.sh

volumes:
  mongodb_data_container:
